### ISSUE TITLE
"An importable Python 2 pip module is required" for pip.installed

### ISSUE THREAD

**Issue by skriesch** [openSUSE/salt#132]
### Description of Issue/Question
The package python-gnupg is necessary to decrypt passwords with gpg in Salt. openSUSE Leap is providing only python-python-gnupg or python3-python-gnupg which are not containing the package for decryption. Therefore I wanted to install that with pip.installed.
After that I received following message:

>       Function: pip.installed
>       Name: python-gnupg
>       Result: False
>      Comment: An importable Python 2 pip module is required but could not be found on your system.      This usually means that the system's pip package is not installed properly.
>      Started: 16:20:59.651024
>     Duration: 1.738 ms
>      Changes:

The package python2-pip is installed on the salt master and on the client.
It seems that is a result of 2018 with urllib3: https://github.com/saltstack/salt/issues/46163#issuecomment-455489847

### Setup

> python-gnupg-installation:
>   pip.installed:
>     - name: python-gnupg
>     - require: 
>        - pkg: gpg-decryption
> 
> gpg-decryption:
>   pkg.installed:
>     - names:
>       - python2-python-gnupg
>       - gpg2
>       - python2-pip

### Steps to Reproduce Issue
1) Install Salt on openSUSE Leap 15.0
2) Create a SLS file with the content above
3) Add any client as a salt-minion
4) Execute (apply) the SLS on the openSUSE system
5) You can not use pip.installed.

### Versions Report
salt 2018.3.2

**Comment by brejoc** [comment]
Thanks for the detailed issue. I've just tried to reproduce this, but it looks like the salt pip module wasn't even activated. You are using Python2 here, but Salt is Python3, right? Did you do something special to make this work with pip2?

**Comment by skriesch** [comment]
Yes. Salt is using pip3 and a python 2 module is required (unimportant whether python 2 or python 3 is installed on openSUSE). Because of this issue I install python 2 on the client. I tried both versions. I have upgraded the version of urllib (as recommended in issues) with pip. Salt is saying that that is not recommended now, but it works now.

Our versions of packages:

> # salt-call --versions-report
> /usr/lib/python3.6/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.5) or chardet (3.0.4) doesn't match a supported version!
>   RequestsDependencyWarning)
> Salt Version:
>            Salt: 2018.3.0
> 
> Dependency Versions:
>            cffi: 1.11.2
>        cherrypy: Not Installed
>        dateutil: Not Installed
>       docker-py: Not Installed
>           gitdb: Not Installed
>       gitpython: Not Installed
>           ioflo: Not Installed
>          Jinja2: 2.10
>         libgit2: 0.26.3
>         libnacl: Not Installed
>        M2Crypto: Not Installed
>            Mako: Not Installed
>    msgpack-pure: Not Installed
>  msgpack-python: 0.5.4
>    mysql-python: Not Installed
>       pycparser: 2.17
>        pycrypto: 2.6.1
>    pycryptodome: Not Installed
>          pygit2: 0.26.0
>          Python: 3.6.5 (default, Mar 31 2018, 19:45:04) [GCC]
>    python-gnupg: 0.4.4
>          PyYAML: 3.12
>           PyZMQ: 17.0.0
>            RAET: Not Installed
>           smmap: Not Installed
>         timelib: Not Installed
>         Tornado: 4.5.3
>             ZMQ: 4.2.3
> 
> System Versions:
>            dist:
>          locale: UTF-8
>         machine: x86_64
>         release: 4.12.14-lp150.12.48-default
>          system: Linux
>         version: Not Installed
>

**Comment by skriesch** [comment]
I have to say that we are using **pip install** as a bash command now. That is a workaround.

**Comment by dwickwire** [comment]
Hmm, I'm having a strikingly similar problem on Ubuntu 18 (bionic) with Flourine (2019.2.0).  I want to use python 3 with the latest version of pip.  In my case I have the same error, but there's an earlier failure also:

> `Error installing 'PyOpenSSL': Could not find a `pip` binary`.

This seems to be due to it trying to install with python 2 instead of python 3 and since there's no pip for python 2 installed things fail.

Here's the log:
```
[INFO    ] Completed state [python3-pip] at time 16:28:38.753647 (duration_in_ms=18.224)
[INFO    ] Running state [PyOpenSSL] at time 16:28:38.756643
[INFO    ] Executing state pip.installed for [PyOpenSSL]
[INFO    ] Executing command ['/usr/bin/python2', u'-m', u'pip', u'--version'] in directory '/home/vagrant'
[ERROR   ] Command '['/usr/bin/python2', u'-m', u'pip', u'--version']' failed with return code: 1
[ERROR   ] stderr: /usr/bin/python2: No module named pip
[ERROR   ] retcode: 1
```

Do you also have the issue with "Could not install pip binary"?

**Comment by skriesch** [comment]
Did you install pip correctly?

**Comment by dwickwire** [comment]
I intentionally didn't install python 2 pip, which I didn't think I needed to for a python 3 salt set up.  See my edit above for more detail.

**Comment by isbm** [comment]
@dwickwire well, `pip` is just another 3rd party module on your target. So obviously, you've got solution already:
```
 Command '['/usr/bin/python2', u'-m', u'pip', u'--version']' failed with return code: 1
```

That said, on your target machine:
1. `/usr/bin/python2 <ENTER>`
2. `import pip` (I assume this will raise you `ImportError`)
3. `pip.__file__` (I assume that won't work for you, but normally it should return you a full path to pip stuff)

**Comment by brejoc** [comment]
@skriesch Are you still seeing this with the current version of Salt?

**Comment by skriesch** [comment]
Leap 15.1 does not have this issue any more.

**Comment by brejoc** [comment]
@skriesch Thanks for checking!
