### ISSUE TITLE
code understanding

### ISSUE THREAD

**Issue by as900** [openSUSE/salt#169]
Hi there, When I was learning and trying to understand the function "build_network_settings" in salt/salt/modules/debian_ip.py, I was confused about the description of the its delivered function. My understanding of this code snippet is "build the global script path". Do I understand that right?

**Comment by brejoc** [comment]
Sorry that this stalled here completely. I hope you found the upstream Slack chat. There is a much better chance to get answers for something like this there. I hope you don't mind that I'm closing this issue.
