### ISSUE TITLE
[BUG] salt-master 3004-9.10 and python310-pyzmq-23.2.0-1.1 issue

### ISSUE THREAD

**Issue by aboe76** [openSUSE/salt#542]
**Description**
salt-master can't connect to zmq bus because of an error in salt/transport/zeromq.py
see: https://github.com/saltstack/salt/pull/62119

**Setup**
salt-master and salt-minion running on opensuse tumbleweed same machine.

Please be as specific as possible and give set-up details.

- [X] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**

start salt-master -l all
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/salt/transport/zeromq.py", line 1020, in _publish_daemon
    pub_sock.setsockopt(zmq.HWM, self.opts.get("pub_hwm", 1000))
  File "zmq/backend/cython/socket.pyx", line 447, in zmq.backend.cython.socket.Socket.set
  File "zmq/backend/cython/socket.pyx", line 279, in zmq.backend.cython.socket._setsockopt
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Invalid argument
```
**Expected behavior**
no errors and salt-master and salt-minion can communicate with each other

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
Salt: 3004

Dependency Versions:
cffi: 1.15.0
cherrypy: 18.6.1
dateutil: 2.8.2
docker-py: Not Installed
gitdb: Not Installed
gitpython: Not Installed
Jinja2: 3.0.3
libgit2: 1.4.3
M2Crypto: 0.38.0
Mako: Not Installed
msgpack: 1.0.4
msgpack-pure: Not Installed
mysql-python: Not Installed
pycparser: 2.21
pycrypto: 3.15.0
pycryptodome: Not Installed
pygit2: 1.9.1
Python: 3.10.5 (main, Jun 06 2022, 22:34:44) [GCC]
python-gnupg: Not Installed
PyYAML: 6.0
PyZMQ: 23.2.0
smmap: Not Installed
timelib: 0.2.4
Tornado: 4.5.3
ZMQ: 4.3.4

System Versions:
dist: opensuse-tumbleweed 20220703 n/a
locale: utf-8
machine: x86_64
release: 5.18.6-1-default
system: Linux
version: openSUSE Tumbleweed 20220703 n/a
```
</details>

**Additional context**

fix is already in saltstack main repo:
https://github.com/void-linux/void-packages/pull/37369

**Comment by mcalmer** [comment]
@meaksh JFYI
