### ISSUE TITLE
Fix for [Errno 0] Resolver Error 0 (no error) (bsc#1087581) has to be update

### ISSUE THREAD

**Issue by brejoc** [openSUSE/salt#78]
There is a fix for this patch in products:next. We also need that in systemsmanagement:saltstack/salt. 

Updated patch in…
- [x] systemsmanagement:saltstack:testing > salt
- [ ] systemsmanagement:saltstack > salt

**Comment by meaksh** [comment]
@brejoc - I'm accepting https://build.opensuse.org/request/show/599740 . This fix should also go upstream, right?

**Comment by brejoc** [comment]
@meaksh Thanks Pablo! Correct. We also need this fix upstream. leas go ahead if you have the time. Otherwise I'll seen when I can do that this week.

**Comment by meaksh** [comment]
https://github.com/saltstack/salt/pull/47294

**Comment by brejoc** [comment]
@kkaempf We've got the update of the patch in systemsmanagement:saltstack:testing > salt, but I would like to promote this to systemsmanagement:saltstack > salt before closing this issue.

**Comment by kkaempf** [comment]
@brejoc as soon as @dincamihai reports Salt tests as passing, promote !
